//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cypher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cypher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAH
        ///AAL
        ///AAS
        ///ABA
        ///ABO
        ///ABS
        ///ABY
        ///ACE
        ///ACT
        ///ADD
        ///ADO
        ///ADS
        ///ADZ
        ///AFF
        ///AFT
        ///AGA
        ///AGE
        ///AGO
        ///AGS
        ///AHA
        ///AHI
        ///AHS
        ///AID
        ///AIL
        ///AIM
        ///AIN
        ///AIR
        ///AIS
        ///AIT
        ///ALA
        ///ALB
        ///ALE
        ///ALL
        ///ALP
        ///ALS
        ///ALT
        ///AMA
        ///AMI
        ///AMP
        ///AMU
        ///ANA
        ///AND
        ///ANE
        ///ANI
        ///ANT
        ///ANY
        ///APE
        ///APO
        ///APP
        ///APT
        ///ARB
        ///ARC
        ///ARE
        ///ARF
        ///ARK
        ///ARM
        ///ARS
        ///ART
        ///ASH
        ///ASK
        ///ASP
        ///ASS
        ///ATE
        ///ATT
        ///AUK
        ///AVA
        ///AVE
        ///AVO
        ///AWA
        ///AWE
        ///AWL
        ///AWN
        ///AXE
        ///AYE
        ///AYS
        ///AZO
        ///BAA
        ///BAD
        ///BAG
        ///BAH
        ///BAL
        ///BAM
        ///BAN
        ///BAP
        ///BAR
        ///BAS
        ///BAT
        ///BAY
        ///BED
        ///BEE
        ///BEG
        ///BEL
        ///BEN
        ///BES
        ///BET
        ///BEY
        ///BIB
        ///BID
        ///BIG
        ///BIN
        ///BIO
        ///BIS
        ///BI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string threeletters {
            get {
                return ResourceManager.GetString("threeletters", resourceCulture);
            }
        }
    }
}
